name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手動実行を許可

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Deno DeployのOIDC認証に必須
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "poke-learn" # Deno Deployのプロジェクト名
          entrypoint: "jsr:@std/http/file-server" # Deno標準の静的ファイルサーバーをエントリーポイントにする
          root: "dist" # サーブする静的アセットのルート
